name: pypsa-zambia-workshops
channels:
- conda-forge
- bioconda
dependencies:
- python>=3.12
- pip

  # main packages
- numpy
- scipy
- pandas>=2
- geopandas>=1
- snakemake-minimal>=9
- snakemake-storage-plugin-http>=0.3
- xarray
- networkx
- yaml
- pyomo
- netcdf4
- pypsa>=0.35.2
- atlite>=0.2.14
- powerplantmatching>=0.6
- rasterio>=1.3.2,<1.4
- pysheds
- pyarrow
- numba

  # interactive python
- ipython
- jupyterlab

  # reading particular file types
- tabula-py
- xlrd
- lxml
- pytables
- pyxlsb
- openpyxl
- libgdal-hdf5
- libgdal-netcdf
- pdf2image
- numexpr
- pyyaml

  # geodata utilities
- shapely>2
- pyepsg
- cartopy>=0.22
- country_converter
- mapclassify

  # plotting
- matplotlib>=3.6
- plotly
- hvplot
- holoviews
- geoviews>=1.10
- graphviz
- fiona
- folium

  # publishing
- jupyter-book<2.0.0
- ghp-import
- pre-commit

- pip:
  - highspy
  - tables
  - pypsa-explorer
