name: deploy

on:
  # Trigger the workflow on push to main branch with changes
  push:
    branches:
    - zambia

permissions:
  pages: write
  deployments: write
  contents: write
  statuses: write
  actions: write
  checks: read

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v5

    # Install dependencies
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: pypsa-zambia-workshops
        channel-priority: strict

    - name: Cache Conda env
      uses: actions/cache@v4
      with:
        path: ${{ env.CONDA }}/envs
        key: conda-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles(format('{0}', env.env_file)) }}
      id: cache-env

    - name: Update environment
      run: |
        conda env update -n pypsa-zambia-workshops -f environment.yaml
        echo "Run conda list" && conda list

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build pypsa-zambia-workshops

    # Deploy the book's HTML to gh-pages branch
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: pypsa-zambia-workshops/_build/html
